const ShopActionsTypes = {
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCSESS: "FETCH_COLLECTIONS_SUCSESS",
  FETCH_COLLECTIONS_FALULURE: "FETCH_COLLECTIONS_FALULURE"
};
export default ShopActionsTypes;
